function toggleMenu(){document.getElementById('nav').classList.toggle('show')}
const guides={
"Brake Pad & Rotor Replacement":`<p><b>Tools:</b> jack stands, lug socket, ratchet, brake tools, torque wrench.</p><ol><li>Park safely, chock wheels and support the vehicle on approved stands.</li><li>Remove the wheel and inspect the brake system before taking anything apart.</li><li>Support the caliper so the brake hose is never used to carry its weight.</li><li>Remove the caliper and pads, then remove the rotor if replacement is required.</li><li>Clean the hub mounting surface and install the new rotor.</li><li>Install the correct pads and hardware. Lubricate only specified contact points.</li><li>Torque fasteners to the vehicle-specific service specification.</li><li>Reinstall the wheel and torque lug nuts in the correct pattern.</li><li>Pump the brake pedal until firm before moving the vehicle.</li><li>Perform a careful low-speed brake test and check for leaks or abnormal noise.</li></ol>`,
"No-Crank Diagnosis":`<ol><li>Confirm the complaint: does the engine crank, or is it completely silent?</li><li>Check battery condition and terminal connections.</li><li>Check power and ground cables for corrosion or voltage drop.</li><li>Verify starter control power while attempting to crank.</li><li>Check the appropriate relay/fuse and neutral-safety or clutch-start circuit.</li><li>Only condemn the starter after the power, ground and control circuits have been tested.</li></ol>`,
"Overheating Diagnosis":`<ol><li>Do not open a hot cooling system.</li><li>After it cools, inspect coolant level and visible leaks.</li><li>Check radiator, hoses, thermostat operation and cooling-fan operation.</li><li>Inspect the water pump and belt drive for leaks or abnormal bearing noise.</li><li>Use a cooling-system pressure test when appropriate.</li><li>If basic checks pass, test for combustion-gas intrusion according to the vehicle procedure.</li></ol>`,
"Front-End Inspection":`<ol><li>Inspect tires and wheel bearings first.</li><li>Check ball joints, tie rods and steering linkage for looseness.</li><li>Inspect control-arm bushings, sway-bar links and shocks/struts.</li><li>Look for broken springs, damaged mounts and leaking dampers.</li><li>After suspension or steering geometry changes, have alignment checked.</li></ol>`,
"Voltage Drop Testing":`<ol><li>Set the multimeter to DC volts.</li><li>Test the positive side of the circuit while the load is operating.</li><li>Test the ground side under the same load.</li><li>Compare the measured drop with the vehicle's service specification.</li><li>Repair corroded connections, damaged cables or poor grounds and retest.</li></ol>`,
"Check Engine Diagnosis":`<ol><li>Scan stored, pending and relevant permanent codes.</li><li>Save freeze-frame information before clearing anything.</li><li>Use the code as a starting point—not proof that the named part is bad.</li><li>Inspect wiring, connectors, power, ground and related systems.</li><li>Test the suspected component and the conditions that can cause the code.</li><li>Repair the root cause, then clear codes when appropriate and complete the required drive cycle.</li></ol>`
};
function showGuide(name){document.getElementById('modalTitle').textContent=name;document.getElementById('modalBody').innerHTML=guides[name]||'<p>Full guide coming soon.</p>';document.getElementById('modal').classList.add('open')}
function hideGuide(){document.getElementById('modal').classList.remove('open')}
function closeGuide(e){if(e.target.id==='modal')hideGuide()}
